projects:
  Farm Details API:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: ap-south-1
        apiId: wfvnmber4zgj7j5jhoy5o64afa
        maxDepth: 2
extensions:
  amplify:
    version: 3
